# Generated by Django 4.2.1 on 2023-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member_paymentdate_member_receiptnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='totalAmount',
            field=models.CharField(max_length=255),
        ),
    ]
